# Generated by Django 4.0.6 on 2022-07-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('app_name', models.CharField(max_length=500)),
                ('app_id', models.CharField(max_length=500)),
                ('image_link', models.CharField(max_length=500)),
            ],
        ),
    ]
