# Generated by Django 4.0.6 on 2022-07-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_apps'),
    ]

    operations = [
        migrations.AddField(
            model_name='appinstalls',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='apps',
            name='image_link',
            field=models.URLField(),
        ),
    ]
