# Generated by Django 4.0.6 on 2022-07-12 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_appinstalls_created_at_alter_apps_image_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appinstalls',
            old_name='date',
            new_name='idate',
        ),
    ]
